// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgdzjksulaezkmhwvkwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnZHpqa3N1bGFlemttaHd2a3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MTkyNTMsImV4cCI6MjA1NzQ5NTI1M30.to-AUwheN20N5OcomXwashkYMFUIw9vLTC_dU0jXxMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);